version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - kafka
      - postgres
      - zookeeper
    networks:
      - kafkanetwork
    environment:
      - KAFKA_ADDRESSES=kafka:9092
      - KAFKA_TOPIC=commits
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=pass
      - DATABASE_NAME=mydb
      - DATABASE_SSL=disable
      - SCRAPPER_SERVICE_HOST=scrapper
      - SCRAPPER_SERVICE_PORT=8082

  scrapper:
    build:
      context: .
      dockerfile: Dockerfile.scrapper
    depends_on:
      - kafka
      - postgres
      - zookeeper
    networks:
      - kafkanetwork
    environment:
      - KAFKA_ADDRESSES=kafka:9092
      - KAFKA_TOPIC=commits
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=pass
      - DATABASE_NAME=mydb
      - DATABASE_SSL=disable
      - SCRAPPER_SERVICE_HOST=0.0.0.0
      - SCRAPPER_SERVICE_PORT=8082


  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafkanetwork
    logging:
      driver: "none"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9092,OUTSIDE://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_NUM_PARTITIONS=1
    networks:
      - kafkanetwork
    logging:
      driver: "none"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=mydb
      - POSTGRES_HOST_AUTH_METHOD=trust  
    ports:
      - "5432:5432"
    networks:
      - kafkanetwork
    logging:
      driver: "none"

networks:
  kafkanetwork:
    driver: bridge
