FROM golang:1.24.1-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/scrapper_bin scrapper/cmd/main/main.go

FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates curl

COPY --from=builder /app/scrapper_bin  ./

COPY kafka_healthcheck.sh ./

RUN chmod +x kafka_healthcheck.sh

COPY .env ./
