{
 "title": "Scrapper Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutines" }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes" }
   ]
  },
  {
   "title": "Total gRPC Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(grpc_requests_total[1m])" }
   ]
  },
  {
   "title": "Total gRPC Error Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(grpc_requests_errors_total[1m])"
    }
   ]
  }
 ]
}