name: Linter and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.24.1'

    - name: Install dependencies
      run: go mod tidy

    - name: Install linters
      run: |
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        go install github.com/uudashr/gocognit/cmd/gocognit@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Run linters
      run: |
        go vet ./...
        gocyclo ./
        gocognit ./
