name: Linter and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.24.1'

    - name: Install dependencies
      run: go mod tidy

    - name: Run linters
      run: go vet ./...

    - name: Run unit tests
      run: go test -tags "unit" ./...
